api(win_config): add nightly open win split support
noib3/nvim-oxi pull request #167
Opened 2024-05-10 19:16 UTC by MyyPo

Noticed that new nightly functionality for `nvim_open_win`  that allows to open regular splits is not possible to use with the crate yet. Hopefully it will be of help. 

Let me know if I missed something.

2024-05-13 00:53 UTC, noib3 requested changes

2024-05-13 00:53 UTC, noib3 commented on tests/src/api/win_config.rs
> +    assert_eq!(config.split, got.split);
I believe we can unwrap both of these to make sure the direction is `Some(SplitDirection::Right)`.

2024-05-13 00:53 UTC, noib3 commented on crates/api/src/types/window_relative_to.rs
> +    #[serde(untagged)]
It seems like this is making the `open_win_basic_config` test fail on 0.8 and 0.9.

2024-05-13 13:32 UTC, myypo commented
I've resolved the non-nightly variant of `open_win_basic_config` test failing. Nightly was ok since it does not rely on [this implementation](https://github.com/noib3/nvim-oxi/blob/8d713660115fee32a0ae724e10a79fb2d6978f30/crates/api/src/types/window_relative_to.rs#L37)

Also added unwraps to all options in `win_config.rs` integration test.

Nightly CI seems to get stuck on integration tests both on this PR and on HEAD as I checked on my fork https://github.com/myypo/nvim-oxi. Will, probably, look into it later.

2024-05-13 15:51 UTC, myypo commented
The PR that broke the CI: https://github.com/neovim/neovim/pull/28432 

The 3 functions in question were marked as experimental so they are likely to change in the future again.

2024-05-14 00:13 UTC, noib3 commented
Great work, thanks.

2024-05-14 00:13 UTC, merged