Cleanup `StringBuilder` methods
noib3/nvim-oxi pull request #211
Opened 2024-12-30 20:24 UTC by airblast-dev

I haven't added the necessary tests yet so marking this as draft.

Many of `StringBuilder`'s methods had logic that really should have been their own function with safe wrappers.
This PR moves some logic to their own methods and allows public calls to allocate space without pushing bytes.

This should also reduce the effect of the memory leaks from `String` as `String::from_bytes` will now only allocate the minimal amount needed. This shouldn't change performance in any call site as the capacity is not stored, meaning no length changes are possible once a `String` is constructed. This only helps to reduce the allocated size where arguments require a `String` and a user calls `String::from_bytes`.

As part of the cleanup a redundant null check was removed from `StringBuilder::push_bytes` as `libc::realloc` already handles the null case.

I have made the commit messages to make things are easy to follow. 
Will mark this ready for review once I have added some tests.

2024-12-31 10:49 UTC, airblast-dev commented
Fixed things locally, will push the latest version with new tests added and existing ones passing.

2024-12-31 13:26 UTC, airblast-dev commented
Added a few safety checks to avoid UB in edge cases. Passes the existing tests and the new ones.

The refactor makes it so `String` either points to null with a length of 0, or points to an allocation with a length bigger than zero. The old version would allocate even when pushing 0 bytes.

Lastly, a `String` allocation is now shrunk to its minimal size when calling `StringBuilder::finish` (this is not done in `StringBuilder::finish_unchecked` for cases where extra capacity is known to not exist such as `String::from_bytes`). 

Should be ready for a review :)

2025-01-01 04:15 UTC, noib3 requested changes
Looks good after comments are addressed and tests pass. Thanks!

2025-01-01 04:15 UTC, noib3 commented on crates/types/src/string.rs
> +        self.cap = new_capacity;
I noticed that the bodies of `reserve` and `reserve_exact` are almost identical. Perhaps we should introduce a new helper method, something like:

```rust
/// Returns the minimum capacity needed to allocate `additional` bytes, or
/// `None` if the current capacity is already large enough.
fn min_capacity_for_additional(&self, additional: usize) -> Option<NonZeroUsize>;
```

And then:
```rust
pub fn reserve(&mut self, additional: usize) {
    let Some(min_capacity) = self.min_capacity_for_additional(additional) else {
      return;
    };
    let Some(new_capacity) = min_capacity
        .checked_next_power_of_two()
        .unwrap_or(min_capacity);
    self.reserve_raw(new_capacity);
}

pub fn reserve_exact(&mut self, additional: usize) {
    if let Some(new_capacity) = self.min_capacity_for_additional(additional) {
        self.reserve_raw(new_capacity);
    }
}
```

Which has the added benefit of making the difference between `reserve` and `reserve_exact`'s implementations much clearer at a glance.

2025-01-01 04:15 UTC, noib3 commented on crates/types/src/string.rs
> +    /// This is marked unsafe as the allocation size should never be zero for portability reasons.
The function can be made safe by including this invariant in the function's signature, i.e.

```rust
fn reserve_raw(&mut self, new_capacity: NonZeroUsize)
```

2025-01-01 04:15 UTC, noib3 commented on crates/types/src/string.rs
> +    unsafe fn reserve_raw(&mut self, by: usize) {
`by` is not very descriptive (I'm not even sure what it stands for). Maybe `new_capacity`?

2025-01-01 04:15 UTC, noib3 commented on crates/types/src/string.rs
> +        self.inner.data = ptr as *mut ffi::c_char;
Updating the capacity is currently left to the callers. Is there a reason for it? I think it should be this function's responsibility.

2025-01-01 04:15 UTC, noib3 commented on crates/types/src/string.rs
> +    }
Strings being leaked is a separate problem which should hopefully be resolved Soon™. I think we should just have a single `finish()` function.

2025-01-01 04:15 UTC, noib3 commented on crates/types/src/string.rs
> +    /// Returns the remaining capacity including the space for a null byte.
Shouldn't this be "excluding" instead of "including"? Although honestly it might be better to just reword it, something like:

```
/// Returns the remaining *usable* capacity, i.e. the remaining capacity minus
/// the space reserved for the null terminator.
```

2025-01-01 08:15 UTC, airblast-dev commented on crates/types/src/string.rs
> +        s.reserve_exact(bytes.len());
Done

2025-01-01 08:18 UTC, airblast-dev commented on crates/types/src/string.rs
> +        self.cap = new_capacity;
Moved the duplicate logic to its own function.

2025-01-01 08:19 UTC, airblast-dev commented on crates/types/src/string.rs
> +    /// Returns the remaining capacity including the space for a null byte.
Yes that was a typo. I just copied over the comment you wrote here.

2025-01-01 08:20 UTC, airblast-dev commented on crates/types/src/string.rs
> +        self.inner.data = ptr as *mut ffi::c_char;
Nope, made it so it updates the capacity.

2025-01-01 09:15 UTC, noib3 requested changes

2025-01-01 09:15 UTC, noib3 commented on crates/types/src/string.rs
> +        // TODO: remove once strings are no longer leaked
I think this was about the previous method.

2025-01-01 09:15 UTC, noib3 commented on crates/types/src/string.rs
> +    pub fn reserve(&mut self, aditional: usize) {
Typo.

2025-01-01 09:15 UTC, noib3 commented on crates/types/src/string.rs
> +    pub fn reserve_exact(&mut self, aditional: usize) {
Same typo.

2025-01-01 09:15 UTC, noib3 commented on crates/types/src/string.rs
> +    /// A check isn't included as all call sites should already handle the case.
This was only relevant to the old function's signature.

2025-01-01 09:15 UTC, noib3 commented on crates/types/src/string.rs
> +    ///     allocation just to store a null byte, we should return null instead)
It made sense to include this info when the function was private, but now this is public and callers don't care about any of it.

2025-01-01 09:15 UTC, noib3 commented on crates/types/src/string.rs
> +        aditional: usize,
Same typo as above.

2025-01-01 09:15 UTC, noib3 commented on crates/types/src/string.rs
> +        }
Is there a reason for special-casing this? It's already handled by the following check.

2025-01-01 09:16 UTC, noib3 commented
Note that a couple of tests are segfaulting.

2025-01-01 09:22 UTC, airblast-dev commented
Yeah, not really sure why. Weird as nothing seems wrong in the String tests. Looking into it.

2025-01-01 11:06 UTC, airblast-dev commented
Looked into the neovim source. Down the call chains the string is copied with `xstrdup` which doesn't handle the null ptr causing segfaults.

Not sure if it was intentional but `String::from_bytes` always allocating even for zero bytes was avoiding this problem.
This also means even `String::new` should allocate in case it is passed somewhere and it is attempted to be copied with `memcpy` or `xstrdup`...

Many of the functions work without an issue but to be safe its likely best to always allocate. For example the failing function relies on the null byte while some of them check the length, in order to even find the null byte the null pointer gets read and causes a segfault or the null pointer is used in a memcpy with mostly the same outcome. 

I originally though that it could be an issue, but `String::new()` returning a null ptr made me think this was fine.

Not really sure what to do from here.

2025-01-01 11:22 UTC, noib3 commented
Having to allocate even for empty strings kinda sucks, but it's an upstream issue. I think, at least for the time being, we should just add a comment explaining why we allocate even when not necessary.

> in order to even find the null byte the null pointer gets read

I'd have to look into it, but why does Neovim even need strings to be null-terminated when they have a `len` field?

2025-01-01 12:18 UTC, airblast-dev commented
> I'd have to look into it, but why does Neovim even need strings to be null-terminated when they have a `len` field?

Not really sure tbh. I will look into the neovim source code again if I'm misunderstanding something or if there is an underlying bug somewhere. Regardless I am pretty sure that null pointers are a no-no. In case you want to try it out, set the minimum argument to `StringBuilder::with_capacity` to 1 inside `String::from_bytes` and all of the tests will pass.

2025-01-01 15:21 UTC, noib3 commented
I'll do some more investigation to better understand strings' usage in Neovim.

As far as this PR is concerned, I say we just remove or comment out the `if cap == 0` check in `StringBuilder::with_capacity()`, which should fix the segfaults.

2025-01-02 15:11 UTC, merged

2025-01-02 15:11 UTC, noib3 commented
Thanks!