Allow getting the buffer handle and make `Buffer` copy
noib3/nvim-oxi pull request #80
Opened 2022-10-22 12:56 UTC by oberblastmeister

Getting the internal handle is useful when `nxim_oxi` hasn't made bindings to something yet. I also don't see why `Buffer` shouldn't be `Copy`, as it's just an integer. I also don't see how the internals of `Buffer` could be changed to something `!Copy` in the future. I think the other types like `Window` should be made `Copy` too.

2023-01-28 00:10 UTC, oberblastmeister commented
@noib3 Is this okay?

2023-01-28 00:13 UTC, noib3 commented
> @noib3 Is this okay?

@oberblastmeister sorry for keeping it open so long, I'll make sure to review this tomorrow.

2023-01-29 22:57 UTC, noib3 requested changes

2023-01-29 22:57 UTC, noib3 commented on crates/nvim-api/src/buffer.rs
> +    pub fn handle(&self) -> BufHandle {
It's missing a doc comment explaining what it returns.

2023-01-29 22:57 UTC, noib3 commented on crates/nvim-api/src/buffer.rs
> +#[derive(Copy, Clone, Eq, PartialEq, Hash, Serialize, Deserialize)]
I'm not against making the handle wrapper types (i.e. `Buffer`, `Window` and `TabPage`) `Copy` (in fact at one point they were), but I'd change them all in the same commit.

2024-06-14 03:42 UTC, noib3 commented
Closed by #176, which added a `fn handle(&self) -> i32` method on `Buffer`, `Window` and `TabPage`.

Neither of those is `Copy` atm, but I think if we were to make them we should also probably change all the methods from taking `&self` and `&mut self` to taking `self`, which is a breaking change.

2024-06-14 03:42 UTC, closed without merging